export const SET_LEADERBOARD_SEARCHQUERY = 'SET_LEADERBOARD_SEARCHQUERY';

export const SET_LEADBOARD_DISPLAY_MODE = 'SET_LEADBOARD_DISPLAY_MODE';

export const SET_LEADERBOARD_SORT_ATTR = 'SET_LEADERBOARD_SORT_ATTR';